version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app:app --host 0.0.0.0 --reload'
    volumes:
      - .:/source
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - EMAIL_API_KEY=${EMAIL_API_KEY}
      - EMAIL_DOMAIN_NAME=${EMAIL_DOMAIN_NAME}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - db
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    image: postgres:13-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres_data: